name: Release VSIX

on:
  push:
    tags:
      - 'v*' # Trigger on tags like v1.0.0, v2.3.4

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm i

      - name: Install vsce globally
        run: npm install -g @vscode/vsce # Install vsce

      #- name: Compile
      #  run: npm run compile

      - name: Package extension
        run: vsce package

      - name: Upload VSIX to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_G }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./*.vsix
          asset_name: vscode-github-tracker-${{ github.ref_name }}.vsix
          asset_content_type: application/zip

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_G }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
