name: Release VSIX

on:
  push:
    tags:
      - 'v*' # Trigger on tags like v1.0.0, v2.3.4

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm i

      - name: Install vsce globally
        run: npm install -g @vscode/vsce # Install vsce

      #- name: Compile
      #  run: npm run compile

      - name: Package extension
        id: package
        run: |
          vsce package --out dist/
          ls -l dist/ # Debug: List files in dist/
          VSIX_FILE=$(find dist -name "*.vsix" -print -quit)
          echo "::set-output name=vsix_file::$VSIX_FILE" # Correct output

      - name: Create Release
        id: create_release
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: release } = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: context.ref,
              name: `Release ${context.ref}`,
              generate_release_notes: true,
            });
            core.setOutput('upload_url', release.upload_url);

      - name: Upload VSIX to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.package.outputs.vsix_file }}
          asset_name: vscode-github-tracker-${{ github.ref_name }}.vsix
          asset_content_type: application/zip
