name: Release VSIX

on:
  push:
    # tags:
    #   - 'v*' # Trigger on tags like v1.0.0, v2.3.4

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm i

      - name: Install vsce globally
        run: npm install -g @vscode/vsce # Install vsce

      #- name: Compile
      #  run: npm run compile

      - name: Package extension
        id: package
        run: |
          VSIX_PATH=$(vsce package --out ./)
          echo "::set-output name=vsix_file::$(echo "$VSIX_PATH" | grep -oP 'Packaged: \K.*')"

      - name: Create Release and Upload VSIX
        id: release_and_upload
        run: |
          # Create Release
          RELEASE_URL=$(gh release create "${{ github.ref }}" --generate-notes --repo ${{ github.repository }} --title "Release ${{ github.ref }}" | grep -oP '{.*"upload_url":.*?"(.*?)"' | sed 's/.*"\(.*\)".*/\1/')
          echo "::set-output name=upload_url::$RELEASE_URL"

          # Package extension
          vsce package --out dist/
          ls -l dist/
          VSIX_FILE=$(find dist -name "*.vsix" -print -quit)

          # Upload VSIX to release
          curl --header "Authorization: token ${{ secrets.TOKEN_G }}" \
               --header "Content-Type: application/zip" \
               --data-binary @"$VSIX_FILE" \
               "$RELEASE_URL?name=vscode-github-tracker-${{ github.ref_name }}.vsix" # Use tag name
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_G }}
